export const HOME = "/"
export const LOGIN = "/login"
export const TRANSLATION = "/translate"
export const PROFILE = "/profile/"
export const DICTIONARY = "/dictionary"
export const ERROR = "/error"
export const FAVORITES = "/dictionary/favorites"
